### ISSUE TITLE
Re-installing reuses old snap

### ISSUE THREAD

**Issue by markbeierl** [canonical/sdcore-upf-operator#14]
I installed UPF machine charm when the snap was at revision 7. I see the following in snap info:
```
tracking:     latest/edge
refresh-date: today at 14:20 UTC
hold:         forever
channels:
  latest/stable:    --
  latest/candidate: --
  latest/beta:      --
  latest/edge:      1.3 2024-03-12 (8)  83MB devmode
installed:          1.3            (7) 105MB devmode,held
```

I removed the charm, and UPF snap remained. Re-deploying the charm re-uses the installed version 7.

Instructions on how to upgrade the charm/snap should be provided.

**Comment by gruyaume** [comment]
Closing as discussed during backlog grooming
