### ISSUE TITLE
Charm does not recover from invalid iface on host

### ISSUE THREAD

**Issue by markbeierl** [canonical/sdcore-upf-operator#23]
I have an `access` and `core` interface on my machine. If I put the interfaces into a `down` state, the up4 script fails in an unusual way. The following log is displayed:
```
Failed to create AF_PACKET socket for access. Exiting...
*** Error: Unhandled exception in the configuration script (most recent call last)
  File "/snap/sdcore-upf/current/opt/bess/bessctl/conf/up4.bess", line 142, in <module>
    p.init_port(idx, parser.mode)
  File "/snap/sdcore-upf/16/opt/bess/bessctl/conf/ports.py", line 204, in init_port
    sys.exit()
SystemExit
  Command failed: run /snap/sdcore-upf/current/opt/bess/bessctl/conf/up4
```

... and then hangs.

So the charm is left waiting and no further action can be taken by Juju until it is cancelled.

**Comment by gatici** [comment]
I tried to reproduce the issue, however it did not appear using upf snap revision 40. 
I performed the  following steps:
1. Installed UPF machine charm
2. when charm status was active, set the access and core interfaces in the UPF machine to down
3. Charm  did not crash but charm status become blocked with the message “Network interfaces are not valid.”
4. Then, active the interfaces again
5. When the update-status hook runs, charm status become to active again.

**Comment by gatici** [comment]
![image-20240419-084149](https://github.com/canonical/sdcore-upf-operator/assets/22467749/b44137ee-becb-4747-bb55-0dd219e8d561)
![image-20240419-084451](https://github.com/canonical/sdcore-upf-operator/assets/22467749/da9172c4-5d4e-41a1-a077-0b9c8a72ca0f)

**Comment by gatici** [comment]
The final charm status become active again after activating the `access` and `core` interfaces.
```
juju status
Model  Controller  Cloud/Region         Version  SLA          Timestamp
upf    lxd-local   localhost/localhost  3.4.2    unsupported  11:45:20+03:00

App         Version  Status  Scale  Charm       Channel  Rev  Exposed  Message
sdcore-upf           active      1  sdcore-upf             1  no       

Unit           Workload  Agent  Machine  Public address  Ports  Message
sdcore-upf/2*  active    idle   4        10.120.57.87           

Machine  State    Address       Inst id              Base          AZ  Message
4        started  10.120.57.87  manual:10.120.57.87  ubuntu@22.04      Manually provisioned machine
```

**Comment by markbeierl** [comment]
I think #27 fixed it.
