### ISSUE TITLE
Bessctl configuration remains hanging

### ISSUE THREAD

**Issue by dariofaccin** [canonical/sdcore-upf-operator#92]
### Bug Description

Sometimes the bess configuration remains hanging.
Running manually the command `sudo sdcore-upf.bessctl run /snap/sdcore-upf/current/opt/bess/bessctl/conf/up4` returns the error provided in the log section. The command does not exit, causing the charm to be hanging forever.

### To Reproduce

1. Deploy `sdcore-upf`

### Environment

Microk8s 1.29
Juju 3.4

### Relevant log output

```shell
Setting up port enp6s0 on worker ids [0]
Failed to create AF_PACKET socket for enp6s0. Exiting...
*** Error: Unhandled exception in the configuration script (most recent call last)
  File "/snap/sdcore-upf/current/opt/bess/bessctl/conf/up4.bess", line 142, in <module>
    p.init_port(idx, parser.mode)
  File "/snap/sdcore-upf/42/opt/bess/bessctl/conf/ports.py", line 204, in init_port
    sys.exit()
SystemExit
  Command failed: run /snap/sdcore-upf/current/opt/bess/bessctl/conf/up4
```

**Comment by gruyaume** [comment]
@dariofaccin is this error still relevant?

**Comment by dariofaccin** [comment]
Closing as it is fixed by https://github.com/omec-project/bess/pull/62
